# 大本はここからぱくりました。https://qiita.com/nouka/items/aae1e68dfe81e4441c4f
# ワークフローの名前
name: Release

# 起動のタイミング
# 今回はmasterブランチへのpush
on:
  push:
    branches:
      - master

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-18.04

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ["14.15.4"]
        python-version: ["3.8.6"]

    # 各ステップの実行
    steps:
      # チェックアウト
      - uses: actions/checkout@v1

      # 使用するnodeのバージョンを指定
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # パッケージのインストールとアプリのビルド
      - name: install and build
        run: |
          cd react
          yarn install
          yarn build
        env:
          CI: true

      # FTPで転送（ここからぱくりました。https://qiita.com/chieeeeno/items/6be835c74d6d7f597c6a）
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0 # FTPを使ってサーバーにDeployするアクションを実行
        env: # FTP環境の設定を行う
          FTP_SERVER: ${{ secrets.FTP_SERVER }} # FTPサーバーのURLを設定
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
          LOCAL_DIR: docs # どのディレクトリのデータをアップロードするか
          REMOTE_DIR: curriculumvitae # リモートのどのディレクトリにアップロードするか
          protocol: ftps-legacy
          ARGS: --delete
